---
- name: "Build image with ansible"
  hosts: localhost
  tasks:  

    - name: remove used image
      command: docker rmi  sami4rhimi/big-data-image
      ignore_errors: true

    - name: build docker image from dockerfile
      command: docker build -t big-data-image  .

    - name: create tag to image
      command: docker tag big-data-image sami4rhimi/big-data-image

    - name: scan image
      command: trivy image --severity CRITICAL sami4rhimi/big-data-image

    - name: push image to dockerhub
      command: docker push sami4rhimi/big-data-image
