apiVersion: v1
kind: Service
metadata:
  name: bigdata-svc
spec:
  selector:
    app: bigdata
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bigdata
  template:
    metadata:
      labels:
        app: bigdata
    spec:
      containers:
      - name: bigdata-cont
        image: sami4rhimi/big-data-image:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080